name: 'WhiteList BlackList'

on:
  schedule:
    - cron: '0 16 * * *' # UTC
  workflow_dispatch:
  repository_dispatch:
    types: whitelist

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ffmpeg-python opencc-python-reimplemented aiohttp tqdm urllib3
          mkdir -p ~/.ssh
          echo -e "${{ secrets.USER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts
          
      - name: Run Python script
        run: |
          git clone git@github.com:wudongdefeng/tv.git tv
          git clone git@github.com:wudongdefeng/groceries.git ad
          git clone git@github.com:wudongdefeng/tvbackup.git tvbox          
          sh tv/diy.sh
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:wudongdefeng/tvbackup.git"
          source_branch: "main"
          destination_repo: "ssh://git@mp.5212496.xyz:1022/wddf/tvbox.git"
          destination_branch: "master"
          
          source_ssh_private_key: ${{ secrets.USER_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.GOGS_SSH }} # optional, will override `SSH_PRIVATE_KEY`
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3     
